{Simulación de un Reactor Discontinuo Mezcla Perfecta con una cinética de Michaelis Menten con inhibicióncompetitiva total por parte del producto}

METHOD RK4

STARTTIME = 0
STOPTIME=240 {min}
DT = 1

{ECUACIONES}

S' = rS

rS = -kcat*eT*S/(KM*(1+P/Kp)+S) {mol/L·min}

x = (S0-S)/S0

P = P0 + S0*x

PP = P*V/(TIME+tM)*60 {mol/h}

{PARAMETROS}

kcat = 1.25 {min-1}
eT = 0.00 {mol/L}
KM = 0.12 {mol/L}
S0 = 2.0 {mol/L}
P0 =0 {mol/L}
V = 200 {L}
tM = 30 {min}
Kp = 0.04 {mol/L} 

{CONDICIONES INICIALES}

INIT S = S0

